### ISSUE TITLE
Startup script

### ISSUE THREAD

**Issue by mbmccoy** [coup-de-foudre/FM_transmitter#12]
When the rasp pi is plugged in, it should start the transmitter at startup and begin accepting audio. The typical method (suggested by Lady Red) is to use `systemd` so that the service will restart when it goes down.

Alternatively, we can just use a startup script and use a "power cycle"  workflow.

**Comment by mcscope** [comment]
I'm gonna take a crack at this once we get our pi up. Shouldn't be hard *famous last words*

**Comment by mbmccoy** [comment]
This was completed in #18
