### ISSUE TITLE
Create warm-up "preamble" to avoid surge

### ISSUE THREAD

**Issue by mbmccoy** [coup-de-foudre/FM_transmitter#2]
From @boothjeffj: 

> Can you add a ‘preamble’/‘prelude’ immediately before playing a music file (i.e. going from no clock to some clock)? The preamble would consist of starting the clock at 650 kHz and ramping down to the requested frequencyMHz over a second or so, and then transitioning to music clock. Doing this will ‘spin up’ the coil gradually without having to use a variac. With full power applied and no drive signal, turning it on suddenly near the center freq can cause a surge that blows the bridge mosfets (happened again tonight).

**Comment by boothjeffj** [comment]
We also need to manage the transition between wav files. The clock needs to be kept on when the eof is reached. See my comments re soft and hard stops under the 'Stop lightning during silence' issue.
