### ISSUE TITLE
Stream music from external source

### ISSUE THREAD

**Issue by mbmccoy** [coup-de-foudre/FM_transmitter#6]
We need a way to stream music from an external source through the transmitter. While the software currently accepts streams from `stdin`, we need a reliable method to get the audio stream onto the Pi. I propose the following requirements:

 - The audio stream should come in via digital means (e.g., fiber) to lower the chance of distortion.
 - Should support a common sampling rate and format (e.g., 44.1 kHz 16-bit mono `.wav`). This format is likely to become the "one true input type".
  - Should support stopping and starting of the stream? (possibly an issue for another ticket)

**Comment by mbmccoy** [comment]
Note: Instead of streaming _files_ in using fiber, we could also stream the clock signal out, so long as the switching rate can handle up to about 1MHz.

**Comment by boothjeffj** [comment]
I see streaming/real-time audio as the following protocol:
Startup - triggered by detection of input energy; same as file soft start.
Pauses - longer than x seconds > detune center freq up 5-10kHz but keep clock running, no modulation ('squelch'); longer than x+y seconds > shut down same as file shutdown.
Resume after pause - energy detected > ramp center freq back up and modulate.

**Comment by eranrund** [comment]
If https://www.amazon.com/VAlinks-External-Surround-Recording-Compatible/dp/B013256ODG/ref=sr_1_4?ie=UTF8&qid=1499729350&sr=8-4&keywords=usb+toslink is supported under Linux/RPi we can use it to provide optical audio input. That's unrelated to how we make the code support realtime input.

**Comment by mbmccoy** [comment]
@eranrund Just ordered one of those. 

I expect the most significant challenge to be reading in to the code with low latency. A quick google suggests that the standard ALSA `arecord` output has 100ms+ delay, which is unacceptable for performance purposes. Won't know until we try it.

@boothjeffj I think that the on/off trigger (aka "noise gate") is conceptually separate from real time input. Real-time input is more about getting low-latency from linux drivers (possibly very hard), and while gating is more about signal processing (somewhat less hard).

**Comment by mbmccoy** [comment]
Works in PR #11.

**Comment by mbmccoy** [comment]
Merged #11
