### ISSUE TITLE
Stop lightning during silence

### ISSUE THREAD

**Issue by mbmccoy** [coup-de-foudre/FM_transmitter#7]
A request from Mike Murphy:

> There's an aspect that could be worth considering also (but not high priority) -- for visual effect, suppressing the corona a bit during intervals of silence, so there's more visibility of the start and stop of each sound.  A little bit analogous to the way a "noise gate" sidechain would work in audio, where the channel is attenuated (or in our FM case, taken further off-resonance) when input goes below a certain threshold.  The threshold would be selected to separate the sounds, but not make the sound feel "clipped" or choppy.

**Comment by boothjeffj** [comment]
Two ways to 'stop' lightning: 1) stop the clock signal ('hard stop'), 2) keep clock running but raise the center frequency substantially, say 2-3x the spread ('soft stop') which would kill the corona but leave the coil live - not safe to touch. Soft stop is the reverse of the preamble soft start - both reduce the electrical stress on the coil electronics. With hard stop the coil is off even though all the electronics are live - safe to touch coil itself. I've determined we _must_ have a soft stop transition between wav files and when -r repeat flag is set -- stopping the clock abruptly often kills mosfets.

**Comment by mbmccoy** [comment]
There is already a shutdown sequence in the code. Adding a soft stop (say, increase the frequency before shutting down the transmitter) before a hard stop seems very reasonable.

**Comment by boothjeffj** [comment]
Thinking about this some more I realize I don't know how 'silence' is currently represented. Is it the center freq square wave, or center+spread freq. The latter yields least power/smallest/quietest corona.

**Comment by mbmccoy** [comment]
Done in #30.
